name: markdown_editor
description: A Flutter app to edit and save markdown files

publish_to: 'none'

version: 2.0.0+8

environment:
  sdk: ^3.9.2
  flutter: 3.35.7

dependencies:
  expandable: ^5.0.1
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_math_fork: ^0.7.4
  flutter_svg: ^2.2.2
  flutter_widget_from_html_core: ^0.17.0
  html: ^0.15.6
  htmltopdfwidgets: ^1.1.3
  intl: any
  markdown: ^7.3.0
  markdown_widget: ^2.3.2+8
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  printing: ^5.14.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true