name: markdown_editor
description: A Flutter app to edit and save markdown files

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  markdown_editable_textinput: ^2.2.0
  flutter_markdown: ^0.6.14
  permission_handler: ^10.2.0
  url_launcher: ^6.1.10
  file_picker: ^5.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true